-- AlterTable
ALTER TABLE `Register` ADD COLUMN `addressPix` VARCHAR(191) NULL,
    ADD COLUMN `addressVerify` VARCHAR(191) NULL,
    ADD COLUMN `emailPIN` VARCHAR(191) NULL,
    ADD COLUMN `emailVerify` VARCHAR(191) NOT NULL DEFAULT 'no',
    ADD COLUMN `idBack` VARCHAR(191) NULL,
    ADD COLUMN `idFront` VARCHAR(191) NULL,
    ADD COLUMN `idVerify` VARCHAR(191) NOT NULL DEFAULT 'no';
