import apple from "../../../../public/img/pair-icon-aapl.img.svg";
import amcholdings from "../../../../public/img/pair-icon-amc.img.svg";
import eurusd from "../../../../public/img/pair-icon-eurusd.img.svg";
import usdjpy from "../../../../public/img/pair-icon-usdjpy.img.svg";
import bitcoin_ from "../../../../public/img/pair-icon-btcusd.img.svg";
import ethereum_ from "../../../../public/img/pair-icon-ethusd.img.svg";
import spx500 from "../../../../public/img/pair-icon-spx500usd.img.svg";
import uk100 from "../../../../public/img/pair-icon-uk100gbp.img.svg";

import trader1 from "../../../../public/img/1703815597.jpeg";
import human from "../../../../public/img/human.png";
import trader2 from "../../../../public/img/1717690645.jpeg";
import trader3 from "../../../../public/img/1717081124.jpeg";
import trader4 from "../../../../public/img/1715845347.jpeg";
import trader5 from "../../../../public/img/1715072264.jpeg";

export const countryList = [
  { id: 1, code: "US", lang: "en" }, // United States
  { id: 2, code: "GB", lang: "en" }, // United Kingdom
  { id: 3, code: "CA", lang: "en" }, // Canada
  { id: 4, code: "AU", lang: "en" }, // Australia
  { id: 5, code: "IN", lang: "en" }, // India
  { id: 6, code: "FR", lang: "fr" }, // France
  { id: 7, code: "DE", lang: "de" }, // Germany
  { id: 8, code: "ES", lang: "es" }, // Spain
  { id: 9, code: "IT", lang: "it" }, // Italy
  { id: 10, code: "JP", lang: "ja" }, // Japan
  { id: 11, code: "CN", lang: "zh" }, // China
  { id: 12, code: "BR", lang: "pt" }, // Brazil
  { id: 13, code: "RU", lang: "ru" }, // Russia
  { id: 14, code: "MX", lang: "es" }, // Mexico
  { id: 15, code: "KR", lang: "ko" }, // South Korea
  { id: 16, code: "ZA", lang: "en" }, // South Africa
  { id: 17, code: "AR", lang: "es" }, // Argentina
  { id: 18, code: "TR", lang: "tr" }, // Turkey
  { id: 19, code: "ID", lang: "id" }, // Indonesia
  { id: 20, code: "SA", lang: "ar" }, // Saudi Arabia
  { id: 22, code: "SE", lang: "sv" }, // Sweden
  { id: 23, code: "NL", lang: "nl" }, // Netherlands
  { id: 24, code: "CH", lang: "de" }, // Switzerland (defaulting to German)
  { id: 25, code: "EG", lang: "ar" }, // Egypt
];

export const currency = [
  { value: "USD", symbol: "$" },
  { value: "CAD", symbol: "$" },
  { value: "EUR", symbol: "€" },
  { value: "GBP", symbol: "£" },
  { value: "AUD", symbol: "$" },
  { value: "BRL", symbol: "R$" },
];

export const countries = [
  { id: "AF", name: "Afghanistan" },
  { id: "AX", name: "Åland Islands" },
  { id: "AL", name: "Albania" },
  { id: "DZ", name: "Algeria" },
  { id: "AS", name: "American Samoa" },
  { id: "AD", name: "Andorra" },
  { id: "AO", name: "Angola" },
  { id: "AI", name: "Anguilla" },
  { id: "AQ", name: "Antarctica" },
  { id: "AG", name: "Antigua and Barbuda" },
  { id: "AR", name: "Argentina" },
  { id: "AM", name: "Armenia" },
  { id: "AW", name: "Aruba" },
  { id: "AU", name: "Australia" },
  { id: "AT", name: "Austria" },
  { id: "AZ", name: "Azerbaijan" },
  { id: "BS", name: "Bahamas" },
  { id: "BH", name: "Bahrain" },
  { id: "BD", name: "Bangladesh" },
  { id: "BB", name: "Barbados" },
  { id: "BY", name: "Belarus" },
  { id: "BE", name: "Belgium" },
  { id: "BZ", name: "Belize" },
  { id: "BJ", name: "Benin" },
  { id: "BM", name: "Bermuda" },
  { id: "BT", name: "Bhutan" },
  { id: "BO", name: "Bolivia (Plurinational State of)" },
  { id: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
  { id: "BA", name: "Bosnia and Herzegovina" },
  { id: "BW", name: "Botswana" },
  { id: "BV", name: "Bouvet Island" },
  { id: "BR", name: "Brazil" },
  { id: "IO", name: "British Indian Ocean Territory" },
  { id: "BN", name: "Brunei Darussalam" },
  { id: "BG", name: "Bulgaria" },
  { id: "BF", name: "Burkina Faso" },
  { id: "BI", name: "Burundi" },
  { id: "CV", name: "Cabo Verde" },
  { id: "KH", name: "Cambodia" },
  { id: "CM", name: "Cameroon" },
  { id: "CA", name: "Canada" },
  { id: "KY", name: "Cayman Islands" },
  { id: "CF", name: "Central African Republic" },
  { id: "TD", name: "Chad" },
  { id: "CL", name: "Chile" },
  { id: "CN", name: "China" },
  { id: "CX", name: "Christmas Island" },
  { id: "CC", name: "Cocos (Keeling) Islands" },
  { id: "CO", name: "Colombia" },
  { id: "KM", name: "Comoros" },
  { id: "CG", name: "Congo" },
  { id: "CD", name: "Congo (Democratic Republic of the)" },
  { id: "CK", name: "Cook Islands" },
  { id: "CR", name: "Costa Rica" },
  { id: "CI", name: "Côte d'Ivoire" },
  { id: "HR", name: "Croatia" },
  { id: "CU", name: "Cuba" },
  { id: "CW", name: "Curaçao" },
  { id: "CY", name: "Cyprus" },
  { id: "CZ", name: "Czechia" },
  { id: "DK", name: "Denmark" },
  { id: "DJ", name: "Djibouti" },
  { id: "DM", name: "Dominica" },
  { id: "DO", name: "Dominican Republic" },
  { id: "EC", name: "Ecuador" },
  { id: "EG", name: "Egypt" },
  { id: "SV", name: "El Salvador" },
  { id: "GQ", name: "Equatorial Guinea" },
  { id: "ER", name: "Eritrea" },
  { id: "EE", name: "Estonia" },
  { id: "ET", name: "Ethiopia" },
  { id: "FK", name: "Falkland Islands (Malvinas)" },
  { id: "FO", name: "Faroe Islands" },
  { id: "FJ", name: "Fiji" },
  { id: "FI", name: "Finland" },
  { id: "FR", name: "France" },
  { id: "GF", name: "French Guiana" },
  { id: "PF", name: "French Polynesia" },
  { id: "TF", name: "French Southern Territories" },
  { id: "GA", name: "Gabon" },
  { id: "GM", name: "Gambia" },
  { id: "GE", name: "Georgia" },
  { id: "DE", name: "Germany" },
  { id: "GH", name: "Ghana" },
  { id: "GI", name: "Gibraltar" },
  { id: "GR", name: "Greece" },
  { id: "GL", name: "Greenland" },
  { id: "GD", name: "Grenada" },
  { id: "GP", name: "Guadeloupe" },
  { id: "GU", name: "Guam" },
  { id: "GT", name: "Guatemala" },
  { id: "GG", name: "Guernsey" },
  { id: "GN", name: "Guinea" },
  { id: "GW", name: "Guinea-Bissau" },
  { id: "GY", name: "Guyana" },
  { id: "HT", name: "Haiti" },
  { id: "HM", name: "Heard Island and McDonald Islands" },
  { id: "VA", name: "Holy See" },
  { id: "HN", name: "Honduras" },
  { id: "HK", name: "Hong Kong" },
  { id: "HU", name: "Hungary" },
  { id: "IS", name: "Iceland" },
  { id: "IN", name: "India" },
  { id: "ID", name: "Indonesia" },
  { id: "IR", name: "Iran (Islamic Republic of)" },
  { id: "IQ", name: "Iraq" },
  { id: "IE", name: "Ireland" },
  { id: "IM", name: "Isle of Man" },
  { id: "IL", name: "Israel" },
  { id: "IT", name: "Italy" },
  { id: "JM", name: "Jamaica" },
  { id: "JP", name: "Japan" },
  { id: "JE", name: "Jersey" },
  { id: "JO", name: "Jordan" },
  { id: "KZ", name: "Kazakhstan" },
  { id: "KE", name: "Kenya" },
  { id: "KI", name: "Kiribati" },
  { id: "KP", name: "Korea (Democratic People's Republic of)" },
  { id: "KR", name: "Korea (Republic of)" },
  { id: "KW", name: "Kuwait" },
  { id: "KG", name: "Kyrgyzstan" },
  { id: "LA", name: "Lao People's Democratic Republic" },
  { id: "LV", name: "Latvia" },
  { id: "LB", name: "Lebanon" },
  { id: "LS", name: "Lesotho" },
  { id: "LR", name: "Liberia" },
  { id: "LY", name: "Libya" },
  { id: "LI", name: "Liechtenstein" },
  { id: "LT", name: "Lithuania" },
  { id: "LU", name: "Luxembourg" },
  { id: "MO", name: "Macao" },
  { id: "MK", name: "North Macedonia" },
  { id: "MG", name: "Madagascar" },
  { id: "MW", name: "Malawi" },
  { id: "MY", name: "Malaysia" },
  { id: "MV", name: "Maldives" },
  { id: "ML", name: "Mali" },
  { id: "MT", name: "Malta" },
  { id: "MH", name: "Marshall Islands" },
  { id: "MQ", name: "Martinique" },
  { id: "MR", name: "Mauritania" },
  { id: "MU", name: "Mauritius" },
  { id: "YT", name: "Mayotte" },
  { id: "MX", name: "Mexico" },
  { id: "FM", name: "Micronesia (Federated States of)" },
  { id: "MD", name: "Moldova (Republic of)" },
  { id: "MC", name: "Monaco" },
  { id: "MN", name: "Mongolia" },
  { id: "ME", name: "Montenegro" },
  { id: "MS", name: "Montserrat" },
  { id: "MA", name: "Morocco" },
  { id: "MZ", name: "Mozambique" },
  { id: "MM", name: "Myanmar" },
  { id: "NA", name: "Namibia" },
  { id: "NR", name: "Nauru" },
  { id: "NP", name: "Nepal" },
  { id: "NL", name: "Netherlands" },
  { id: "NC", name: "New Caledonia" },
  { id: "NZ", name: "New Zealand" },
  { id: "NI", name: "Nicaragua" },
  { id: "NE", name: "Niger" },
  { id: "NG", name: "Nigeria" },
  { id: "NU", name: "Niue" },
  { id: "NF", name: "Norfolk Island" },
  { id: "MP", name: "Northern Mariana Islands" },
  { id: "NO", name: "Norway" },
  { id: "OM", name: "Oman" },
  { id: "PK", name: "Pakistan" },
  { id: "PW", name: "Palau" },
  { id: "PS", name: "Palestine, State of" },
  { id: "PA", name: "Panama" },
  { id: "PG", name: "Papua New Guinea" },
  { id: "PY", name: "Paraguay" },
  { id: "PE", name: "Peru" },
  { id: "PH", name: "Philippines" },
  { id: "PN", name: "Pitcairn" },
  { id: "PL", name: "Poland" },
  { id: "PT", name: "Portugal" },
  { id: "PR", name: "Puerto Rico" },
  { id: "QA", name: "Qatar" },
  { id: "RE", name: "Réunion" },
  { id: "RO", name: "Romania" },
  { id: "RU", name: "Russian Federation" },
  { id: "RW", name: "Rwanda" },
  { id: "BL", name: "Saint Barthélemy" },
  { id: "SH", name: "Saint Helena, Ascension and Tristan da Cunha" },
  { id: "KN", name: "Saint Kitts and Nevis" },
  { id: "LC", name: "Saint Lucia" },
  { id: "MF", name: "Saint Martin (French part)" },
  { id: "PM", name: "Saint Pierre and Miquelon" },
  { id: "VC", name: "Saint Vincent and the Grenadines" },
  { id: "WS", name: "Samoa" },
  { id: "SM", name: "San Marino" },
  { id: "ST", name: "Sao Tome and Principe" },
  { id: "SA", name: "Saudi Arabia" },
  { id: "SN", name: "Senegal" },
  { id: "RS", name: "Serbia" },
  { id: "SC", name: "Seychelles" },
  { id: "SL", name: "Sierra Leone" },
  { id: "SG", name: "Singapore" },
  { id: "SX", name: "Sint Maarten (Dutch part)" },
  { id: "SK", name: "Slovakia" },
  { id: "SI", name: "Slovenia" },
  { id: "SB", name: "Solomon Islands" },
  { id: "SO", name: "Somalia" },
  { id: "ZA", name: "South Africa" },
  { id: "GS", name: "South Georgia and the South Sandwich Islands" },
  { id: "SS", name: "South Sudan" },
  { id: "ES", name: "Spain" },
  { id: "LK", name: "Sri Lanka" },
  { id: "SD", name: "Sudan" },
  { id: "SR", name: "Suriname" },
  { id: "SJ", name: "Svalbard and Jan Mayen" },
  { id: "SZ", name: "Swaziland" },
  { id: "SE", name: "Sweden" },
  { id: "CH", name: "Switzerland" },
  { id: "SY", name: "Syrian Arab Republic" },
  { id: "TW", name: "Taiwan, Province of China" },
  { id: "TJ", name: "Tajikistan" },
  { id: "TZ", name: "Tanzania, United Republic of" },
  { id: "TH", name: "Thailand" },
  { id: "TL", name: "Timor-Leste" },
  { id: "TG", name: "Togo" },
  { id: "TK", name: "Tokelau" },
  { id: "TO", name: "Tonga" },
  { id: "TT", name: "Trinidad and Tobago" },
  { id: "TN", name: "Tunisia" },
  { id: "TR", name: "Turkey" },
  { id: "TM", name: "Turkmenistan" },
  { id: "TC", name: "Turks and Caicos Islands" },
  { id: "TV", name: "Tuvalu" },
  { id: "UG", name: "Uganda" },
  { id: "UA", name: "Ukraine" },
  { id: "AE", name: "United Arab Emirates" },
  { id: "GB", name: "United Kingdom of Great Britain and Northern Ireland" },
  { id: "US", name: "United States of America" },
  { id: "UM", name: "United States Minor Outlying Islands" },
  { id: "UY", name: "Uruguay" },
  { id: "UZ", name: "Uzbekistan" },
  { id: "VU", name: "Vanuatu" },
  { id: "VE", name: "Venezuela (Bolivarian Republic of)" },
  { id: "VN", name: "Viet Nam" },
  { id: "VG", name: "Virgin Islands (British)" },
  { id: "VI", name: "Virgin Islands (U.S.)" },
  { id: "WF", name: "Wallis and Futuna" },
  { id: "EH", name: "Western Sahara" },
  { id: "YE", name: "Yemen" },
  { id: "ZM", name: "Zambia" },
  { id: "ZW", name: "Zimbabwe" },
];

export const favorites = [
  { id: 1, svg: apple, name: "Apple", desc: "AAPL" },
  { id: 2, svg: amcholdings, name: "AMC Holdings", desc: "AMC" },
  { id: 3, svg: eurusd, name: "EURUSD", desc: "EURUSD" },
  { id: 4, svg: usdjpy, name: "USDJPY", desc: "USDJPY" },
  { id: 5, svg: bitcoin_, name: "Bitcoin", desc: "BTCUSD" },
  { id: 6, svg: ethereum_, name: "Ethereum", desc: "ETHUSD" },
  { id: 7, svg: spx500, name: "S&P 500", desc: "SPX500USD" },
  { id: 8, svg: uk100, name: "UK 100", desc: "UK100GBP" },
];

export const tradersList = [
  {
    id: 1,
    img: trader1,
    name: "TRADAMAX",
    winrate: "96.22",
    profitshare: "20",
  },
  {
    id: 2,
    img: human,
    name: "Charting",
    winrate: "79.50",
    profitshare: "20",
  },
  {
    id: 3,
    img: trader2,
    name: "Aronvorsouw",
    winrate: "94.09",
    profitshare: "20",
  },
  {
    id: 4,
    img: trader3,
    name: "LA CAPSULE",
    winrate: "91.06",
    profitshare: "20",
  },
  {
    id: 5,
    img: trader4,
    name: "Altaz(Boursikotons)",
    winrate: "95.51",
    profitshare: "7",
  },
  {
    id: 6,
    img: trader5,
    name: "Swiat crypto",
    winrate: "93.01",
    profitshare: "20",
  },
];

export const TradeSelectFirst = [
  "Crypto (43)",
  "Currencies (32)",
  "Stocks (94)",
  "Indices (7)",
];

export const TradeSelectSecond = {
  "Crypto (43)": [
    "SOLUSD",
    "BTCUSD",
    "ETHUSD",
    "ADAUSD",
    "LTCUSD",
    "APEUSD",
    "XRPUSD",
    "BCHUSD",
    "MATICUSD",
    "BNBUSD",
    "ATOMUSD",
    "MKRUSD",
    "ZECUSD",
    "AXSUSD",
    "RUNEUSD",
    "KSMUSD",
    "FTMUSD",
    "CAKEUSD",
    "UNIUSD",
    "ICPUSD",
    "NEARUSD",
    "DOTUSD",
    "MANAUSD",
    "XLMUSD",
    "GRTUSD",
    "NEOUSD",
    "LINKUSD",
    "TRXUSD",
    "EGLDUSD",
    "EOSUSD",
    "HBARUSD",
    "DASHUSD",
    "ALGOUSD",
    "XTZUSD",
    "FILUSD",
    "BSVUSD",
    "XMRUSD",
    "COMPUSD",
    "WBTCUSD",
    "AAVEUSD",
    "FTTUSD",
    "KLAYUSD",
    "THETAUSD",
  ],
  "Currencies (32)": [
    "OANDA:AUDCAD",
    "OANDA:AUDCHF",
    "OANDA:AUDJPY",
    "OANDA:AUDNZD",
    "OANDA:AUDUSD",
    "OANDA:CADCHF",
    "OANDA:CADJPY",
    "OANDA:EURAUD",
    "OANDA:EURCAD",
    "OANDA:EURCHF",
    "OANDA:EURGBP",
    "OANDA:EURJPY",
    "OANDA:EURNZD",
    "OANDA:EURUSD",
    "OANDA:GBPAUD",
    "OANDA:GBPCAD",
    "OANDA:GBPCHF",
    "OANDA:GBPJPY",
    "OANDA:GBPNZD",
    "OANDA:GBPUSD",
    "OANDA:NZDCAD",
    "OANDA:NZDCHF",
    "OANDA:NZDJPY",
    "OANDA:NZDUSD",
    "OANDA:USDCAD",
    "OANDA:USDCHF",
    "OANDA:USDJPY",
    "OANDA:USDMXN",
    "OANDA:USDSGD",
    "OANDA:USDTRY",
    "OANDA:USDTHB",
    "OANDA:USDZAR",
  ],
  "Stocks (94)": [
    "Apple",
    "Abbott Labs",
    "Adobe",
    "Analog Devices",
    "AETHLON MEDICAL",
    "AIG",
    "AMC Holdings",
    "AMD",
    "American Tower",
    "Amazon",
    "ALPHA PRO TECH",
    "ASML",
    "Aterian INC",
    "American Express",
    "Boeing",
    "Alibaba",
    "Bank of America",
    "Baidu INC",
    "Bristol Myers",
    "Citigroup",
    "Caterpiller",
    "Clear Channel Outdoor",
    "Camber Energy",
    "Chewy Inc",
    "Colgate-Palmolive",
    "China Liberal",
    "Comcast",
    "COSTCO",
    "Cardiff Oncology INC",
    "Salesforce Inc",
    "Cisco",
    "Chevron",
    "Disney",
    "ebay",
    "Facebook",
    "Fedex",
    "Fastly Inc",
    "General Electric",
    "GEVO INC",
    "General Motors",
    "Google",
    "Goldman Sachs",
    "Home Depot",
    "Honeywell",
    "IBM",
    "Inmode LTD",
    "Intel",
    "Johnson & Johnson",
    "JP Morgan",
    "Coca Cola",
    "Lennar Corporation",
    "Las Vegas Sands",
    "Mastercard",
    "McDonald's",
    "Mondelez International",
    "3M Company",
    "Monster Beverage",
    "Altria Group",
    "MARIN SOFTWARE",
    "Merck",
    "Morgan Stanley",
    "Microsoft",
    "Motorola",
    "Netflix",
    "Nike",
    "Nvidia",
    "Novartis",
    "Oracle",
    "Pepsico",
    "Pfizer",
    "Procter & Gamble",
    "PayPal Inc",
    "Ferrari",
    "Rocket Lab USA INC",
    "Ralph Lauren",
    "REWALK ROBOTICS",
    "Starbucks",
    "Snap Inc",
    "SSR Mining",
    "Square",
    "At&t",
    "Teva",
    "Toyota Motor",
    "T-Mobile US",
    "TripAdvisor",
    "Tesla",
    "TSMC",
    "Twitter",
    "United Health Group",
    "Visa",
    "Verizon",
    "Wells Fargo",
    "Walmart",
    "Exxon Mobil",
  ],
  "Indices (7)": [
    "S&P 500 Index",
    "US Wall St 30",
    "Germany 30",
    "US Nas 100",
    "UK100GBP",
    "US ROSS 2000",
    "Australia 200",
  ],
};

export const TradeSelectThird = ["Native", "Simple", "Technical"];
